first_name=input("please enter your name: ")
last_name=input("please enter your last name: ")
age=input("How old are you "+ first_name+'?')
print("Hello",first_name, last_name, "nice to meet you!")
print(first_name,'you were born in the year', 2024-int(age))
